### ISSUE TITLE
useAuth composable not recognized as an exported member from @okta/okta-vue

### ISSUE THREAD

**Issue by dcb99** [okta/okta-vue#109]
### Describe the bug?

The useAuth composable is not recognized as an exported member from @okta/okta-vue
![image](https://user-images.githubusercontent.com/31573956/190223148-853b2382-9c31-4a3e-8d82-ef2598ff7376.png)

### What is expected to happen?

the composable is found or usable

### What is the actual behavior?

composable is not found or usable 

### Reproduction Steps?

attempt to use the `useAuth` composable in a setup function in a vue component

### SDK Versions

@okta/okta-vue - 5.3.0
@okta/okta-auth-js - 6.8.0
@okta/okta-signin-widget - 6.7.0
vue - 3.2.13

### Execution Environment

macOS, browser

**Comment by jaredperreault-okta** [comment]
`useAuth` was added in `5.4`, which hasn't been released yet. I'll work on getting it released

**Comment by dcb99** [comment]
@jaredperreault-okta thanks for the info, looking forward to being able to use the composable.

**Comment by jaredperreault-okta** [comment]
@dcb99 `5.4.0` has been released
