### ISSUE TITLE
Support disabling Options API via Bundler Build Feature Flags 

### ISSUE THREAD

**Issue by nmarshall23** [okta/okta-vue#128]
### Describe the feature request?

Okta-Vue plugin is dependant on a mixin. This means it's not compatible with the Vue [Bundler Build Feature Flags](https://github.com/vuejs/core/blob/main/packages/vue/README.md#bundler-build-feature-flags), that disables the Vue Options API. Disabling the Options API results in a performance improvement.

Another concern is that the mixins' functions created, and beforeCreate are run by every component. This also means that handleAuthStateUpdate is being subscribed and unsubscribed by every component. 

My suggestion is to move setup logic outside of the mixin. Add router to `OktaVueOptions` definition. 

Example code for setup logic.

```
const authStateRef = shallowRef(oktaAuth.authStateManager.getAuthState())
// use shallowRef because we don't need to make authState deeply reactive. 
// we are only updating authStateRef via handleAuthStateUpdate so we have no need for deep reactivity.

oktaAuth.authStateManager.subscribe(handleAuthStateUpdate)

async function handleAuthStateUpdate(authState: AuthState) {
  authStateRef.value = authState
  triggerRef(authStateRef)
}
```

Make the mixin have minimal code like this:
```
if (typeof __VUE_OPTIONS_API__ !== 'boolean' || __VUE_OPTIONS_API__) {
  app.mixin({
    computed: {
       $authState() { return authStateRef.value }
    }
})
}
```

Another option would be to add a flags to use the Mixin or [Provide](https://vuejs.org/api/application.html#app-provide).
The provide code would look like:
```
export const authStateKey = Symbol('OktaAuthState') as InjectionKey<AuthState>
if (useProvideApiFlag) {
  app.config.unwrapInjectedRef = true // see note
  app.provide(authStateKey, authStateRef)
{
if (useMixinApiFlag) {
 // .. mixin code from above.
}
```

Note, unwrapInjectedRef is a [Temporary Config](https://vuejs.org/guide/components/provide-inject.html#working-with-reactivity), that will be removed in vue 3.3. This note is only shown in the options api doc's.

### New or Affected Resource(s)

`/src/okta-vue.ts`

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this feature request with detailed description.
Internal ref: OKTA-600247

**Comment by denysoblohin-okta** [comment]
Please upgrade to okta-vue 5.7.0
