### ISSUE TITLE
Auth plugin getUser() returns undefined rather than the currently authenticated instance.

### ISSUE THREAD

**Issue by CVANCGCG** [okta/okta-vue#15]
## I'm submitting a:

- [X ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Our Vue single page application uses @okta/okta-vue's Auth plugin to ensure only authenticated users are granted access. The error observed is that calling Auth.getUser() returns **undefined** within our route guards that attempts to inspect who the currently authenticated user and what claims exist to perform authorization.
## Expected behavior

I expect the response from **Auth.getUser()** to return the object that represents the authenticated user with her/his set of claims. This usually happens but at times returns an undefined instance. In troubleshooting, I've observed cases where the accessToken is defined while the idToken is undefined. This may reflect that our accessToken expires in 3 hour windows; whereas, our idToken seems to expire every hour. Am I misunderstanding or does this [function here in the Auth plugin](https://github.com/okta/okta-vue/blob/master/src/Auth.js#L115--L122) fail every time this condition; namely, when accessToken is defined but idToken is undefined arises -- roughly 2 out of every 3 hours?

Extensive Troubleshooting has led to many posts and experiment code changes. We're currently considering applicability of [this reported issue here](https://github.com/okta/okta-oidc-js/issues/460).

**Question**: how do we ensure that the authenticated user is always returned and how is the response from getUser() handle the case where the idToken expiration is shorter lived affect the accessToken expiration? Is this an anomalous condition that should never occur?

## Minimal reproduction of the problem with instructions

1. Create new vue application 
2. Add this route initializer
**Note**: In the code snippet below, you see that our initialization of the Auth plugin uses defaults that result in **autoRenew: true** and the use of local storage. And because our application displays confidential data, we take a vigilant approach to checking the user on each route change that uses the router::beforeEach() and router::beforeResolve() event hooks. The intent is to ensure we authenticate users and renew session tokens via router::beforeEach() event and subsequently invalidate/synchronize the user in the router::beforeResolve() event handler.

```
import Auth from '@okta/okta-vue'
import store from '@state/store'

Vue.use(Auth, {
  issuer: process.env.VUE_APP_OKTA_ISSUER_URL,
  clientId: process.env.VUE_APP_OKTA_CLIENT_ID,
  redirectUri: `${window.location.origin}/implicit/callback`,
  scopes: ['openid', 'profile', 'email'],
  pkce: true,
})


Vue.use(VueRouter)
Vue.use(VueMeta, {
  // The component option name that vue-meta looks for meta info on.
  keyName: 'page',
})

const router = new VueRouter({
  routes: allRoutes,
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition
    } else {
      return { x: 0, y: 0 }
    }
  },
})
```
3. Add these pre and post route guards to ensure only authenticated users are granted access
```
router.beforeEach(Vue.prototype.$auth.authRedirectGuard())

router.beforeResolve(async (routeTo, routeFrom, next) => {
  // Fetch actively logged in use from IDP and conditionally update store
  const authenticatedIDPUser = await Vue.prototype.$auth.getUser()
  if (!authenticatedIDPUser) {
    debugger
    alert('[router.beforeResolve] "$auth.getUser()" returned null/undefined')
  }
  const isAuthorizedUserLoggedIn = store.getters['auth/isLoggedIn']
  const synchronizeUserStoreRequired = authenticatedIDPUser && !isAuthorizedUserLoggedIn
  if (synchronizeUserStoreRequired) {
    await store.dispatch('auth/onLoggedIn', Vue.prototype.$auth)
  }

  // If we reach this point, continue resolving the route.
  next()
})
```
4. start application via ``npm run serve``
5. put a breakpoint in the router.beforeResolve function and notice the triggering of this condition here:
```
if (!authenticatedIDPUser) {
    debugger
    alert('[router.beforeResolve] "$auth.getUser()" returned null/undefined')
  }
```
## Extra information about the use case/user story you are trying to implement

This causes our web application to think we don't have an authenticated user despite the underlying accessToken being valid as evidenced by what's saved in Local Storage.

## Environment
- Package version: 1.1.1
- Vue version: 2.6.10
- Browser: Chrome
- OS: MacOS Mojave, i.e. OSX 10.14.5
- Node version (`node -v`): 12.0.0
- Other:

**Comment by CVANCGCG** [comment]
![image](https://user-images.githubusercontent.com/52972314/86283361-c7831800-bb95-11ea-92aa-2020b3dc7146.png)

**Comment by swiftone** [comment]
Similar to https://github.com/okta/okta-oidc-js/issues/713

Internal ref: OKTA-288360

**Comment by aarongranick-okta** [comment]
@CVANCGCG We believe this issue should be corrected in @okta/okta-vue version >= 3 and @okta/okta-auth-js version >= 4.1

**Comment by jaredperreault-okta** [comment]
@jowens1 Can you please create a new issues and provide as many details as possible? Thanks
