### ISSUE TITLE
Old way of adding global properties not accepted with Vue@3.0.0

### ISSUE THREAD

**Issue by akolybelnikov** [okta/okta-vue#38]
## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Importing `OktaVue` from `@okta/okta-vue` breaks a Vue v.3 app with the error `Uncaught TypeError: Vue.prototype is undefined`.

## Expected behavior
The library should work with Vue v.3. It is necessary to update how the library is plugged-in: from `Vue.prototype.$auth = oktaAuth;` to how it is described in the [documentation](https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties).

## Minimal reproduction of the problem with instructions
Initialize a new Vue app v.3, import the library as described and try serving the app.

## Environment

- Package version: 3.0.0
- Vue version: 3.0.0
- Browser: Firefox
- OS: MacOS
- Node version (`node -v`): 12.16.2
- Other: @okta/okta-auth-js version: 4.3.0

**Comment by oleksandrpravosudko-okta** [comment]
thanks for bringing this up @akolybelnikov

Internal Ref:
OKTA-353048

**Comment by yashints** [comment]
Is there any workaround folks can use in the meantime?

**Comment by mraible** [comment]
There's a PR in-progress for this feature. https://github.com/okta/okta-vue/pull/43

**Comment by denysoblohin-okta** [comment]
@akolybelnikov @yashints 
Support of Vue 3 and Vue Router 4 was introduced in okta-vue 4.0.0
See [migration guide](https://github.com/okta/okta-vue/blob/master/MIGRATING.md#from-version-3x-to-4x)
Can you confirm it works for your Vue 3 projects?
