### ISSUE TITLE
Route is not protected on initial load 

### ISSUE THREAD

**Issue by mMajch** [okta/okta-vue#40]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [] Other (Describe below)

## Current behavior

The library does not protect the route on the initial page load although the flag `requiresAuth: true` is provided. The beforeRouteEnter function (in `node-modules/@okta/okta-vue/src/okta-vue.js`) is not triggered. I noticed that it starts working after navigating. 

My router.ts:
```
import Vue from 'vue';
import Router, { RouteConfig } from 'vue-router';
import authMiddleware from './middlewares/auth';
import { OktaAuth } from '@okta/okta-auth-js'
import OktaVue, { LoginCallback } from '@okta/okta-vue'
import Home from './views/Home.vue'

Vue.use(Router);

const oktaAuth = new OktaAuth({
  issuer: process.env.VUE_APP_OKTA_ISSUER,
  clientId: process.env.VUE_APP_OKTA_CLIENT_ID,
  redirectUri: window.location.origin + '/okta-auth',
  scopes: ['openid', 'profile', 'email'],
  pkce: true,
})

Vue.use(OktaVue, { oktaAuth});

const navRoutes = [
  {
    path: '/',
    name: 'home',
    component: Home,
    meta: {
      requiresAuth: true,
    },
  },
  {
    path: '/okta-auth',
    component: LoginCallback,
  },
] as RouteConfig[];

const router = new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: navRoutes,
});

export default router
```

**BUT**

It works just fine when I do lazy route loading. I simply replaced `import Home from './views/Home.vue'` with `const Home = () => import('./views/Home.vue')` and **the initial route is protected.**

## Expected behavior

If `requiresAuth: true` is provided the initial route should be protected without lazy route loading.

## Minimal reproduction of the problem with instructions

I tried to reproduce it in example apps but didn't manage it yet

## Extra information about the use case/user story you are trying to implement

I tried to reproduce the error in okta-hosted-login from https://github.com/okta/samples-js-vue but I didn't manage to. I can't find out what is the difference between my and the example app. Nevertheless, the issue may occur so I think it's worth reporting. 

## Environment

- Package version: 3.0.0
- Vue version: 2.6.12
- Browser: chrome
- OS: 10.15.4
- Node version (`node -v`): 13.7.0
- Other: vue-router: 3.4.9

**Comment by oleksandrpravosudko-okta** [comment]
thanks for reporting this @mMajch
I will try reproducing with Router configuration you provided

**Comment by oleksandrpravosudko-okta** [comment]
@mMajch this is an issue with v3.0.0
it appears that by the time vue-router performs [`beforeRouteEnter`](https://github.com/vuejs/vue-router/blob/314d09b5f80edadd77b11351c3f1757c70622e12/dist/vue-router.esm.js#L2333) guards lookup, the [auth mixin](https://github.com/okta/okta-vue/blob/master/src/okta-vue.js#L54) has not been applied yet

until this is fixed, you could try using v2.1.1 or proceed with lazy route loading workaround

thanks for drawing attention to this!
Internal Ref:
OKTA-354263

**Comment by shuowu** [comment]
@mMajch Looks like you are using typescript with okta-vue, we are working on a PR to support typescript in the SDK properly. You can track the progress here: https://github.com/okta/okta-vue/pull/39

Also, for the trick you will need to do with the protected route component, see here: https://github.com/okta/okta-vue/pull/39/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R267

**Comment by shuowu** [comment]
@mMajch okta-vue version 3.1 (with ts support) has been released. You can follow https://github.com/okta/okta-vue#use-typescript-with-protected-route to protect your routes with typescript.

You can also check the [test app](https://github.com/okta/okta-vue/tree/master/test/app) as a sample for TypeScript usage.

**Comment by mMajch** [comment]
@shuowu Great news, works like a charm!
