### ISSUE TITLE
Is there any way to protect whole Vue application? 

### ISSUE THREAD

**Issue by ilgiznurgaliev** [okta/okta-vue#42]
Hi,

Currently I have to add `requiresAuth: true` meta attribute to each route and use `NavigationGuardMixin` instead of `Vue` to extend all components, because all paths of my application must be protected.
Is there any way to protect the whole application and get user details in `App` parent component instead?

## Environment

- Package version: 3.1.0
- Vue version: 2.6.11 (using with **TypeScript**)
- Browser: latest Chrome or Firefox
- OS: ArchLinux (latest)
- Node version (`node -v`): v15.5.0

**Comment by shuowu** [comment]
@ilgiznurgaliev You probably can try [nested routes](https://router.vuejs.org/guide/essentials/nested-routes.html) from vue-router. In this way, you can keep the navigation guard logic only on the top level of the routes.

**Comment by ilgiznurgaliev** [comment]
thank you @shuowu, in my case seems this is simplest solution. Just did some tests, works as expected now.

**Comment by shuowu** [comment]
Great! Close the issue for now.
