### ISSUE TITLE
Are you able to use okta/vue for Identity Provider authorize URL's

### ISSUE THREAD

**Issue by LOUKOUKOU** [okta/okta-vue#49]
When looking at this page, it has more fields than the one in you example:

https://developer.okta.com/docs/guides/add-an-external-idp/google/create-authz-url/

 Can you add all these fields into the config like so: 

```
const oktaAuth = new OktaAuth({
  clientId: '',
  issuer: 'https://dev-122233.okta.com/oauth2/v1/authorize',
  idp: '',
  redirectUri: '://{HOST}/implicit/callback',
  responseType: 'id_token',
  responseMode: 'fragment',
  state: 'AASD',
  nonce: 'QWER',
  scopes: ['openid', 'profile', 'email'],
  pkce: true
})
```

**Comment by LOUKOUKOU** [comment]
As soon as I use the 

```
https://dev-123344.okta.com/oauth2/v1/authorize
```

instead of the 

```
https://dev-123344.okta.com/oauth2/default
```

url in issuer it throws an AuthApiError without a message.

**Comment by oleksandrpravosudko-okta** [comment]
Hi @LOUKOUKOU,

`'https://dev-122233.okta.com/oauth2/v1/authorize'` is not a valid issuer value. You could either specify org authorization server (`https://dev-123344.okta.com`) or custom authorization server (`https://dev-123344.okta.com/oauth2/default`).

Authorization parameters can be passed into `signInWithRedirect` (available in [okta-vue@3.x](https://github.com/okta/okta-vue/blob/master/MIGRATING.md#explicitly-accepts-oktaauth-instance-from-config) though OktaAuth instance).

```
oktaAuth.signInWithRedirect({
      state: 'AASD',
      nonce: 'QWER',
      scopes: ['openid', 'profile', 'email'],
      idp: 'idpIdInOkta',
 })

**Comment by LOUKOUKOU** [comment]
@oleksandrpravosudko-okta 

Will it know to use the https://dev-122233.okta.com/oauth2/v1/authorize url?

**Comment by oleksandrpravosudko-okta** [comment]
Yes, with issuer parameter passed to `OktaAuth` constructor, `signInWithRedirect` should navigate to `/authorize` URL.

**Comment by aarongranick-okta** [comment]
@LOUKOUKOU The config options for OktaAuth do not match exactly to the query parameters for the authorize URL. Documentation for OktaAuth options is here: https://github.com/okta/okta-auth-js#configuration-options

Most values have reasonable defaults and should not be set explicitly. The only options required for OIDC flow are `issuer`, `clientId` and `redirectUri`.
