### ISSUE TITLE
Sample project with Semantic UI, jQuery webpack error.

### ISSUE THREAD

**Issue by colby02184** [okta/okta-vue#58]
## I'm submitting a:

- [ ] Other (Describe below)

## Current behavior

I created a project with the okta cli and the command I used was okta start vue. The projected was created correctly and I was even able to log in to my okta org. The problem I have is with Semantic UI which is a dependency in the sample project, for example when I add Semantic UI's jQuery form validations to one of my components, webpack throws the error below. It does look like jQuery is part of the sample project, however, I can't seem to get around the error, even after importing jQuery directly on the component.

TypeError: jquery__WEBPACK_IMPORTED_MODULE_0___default(...)(...).form is not a function"

## Expected behavior

I should be able to use jQuery in the sample project that's created when doing okta create vue.

## Minimal reproduction of the problem with instructions

You should be able to reproduce the issue by just dropping in one of Semantic UI's form and include some of their jQuery validation code for the form. I went to https://semantic-ui.com/behaviors/form.html to grab that code.

## Environment

- Package version:
- Vue version: 2.6.12
- Browser: Chrome 90.0.4430.93
- OS: Windows 10 Pro
- Node version (`node -v`): v16.0.0
- Other: okta cli version 0.7.1-1f9781e

**Comment by shuowu** [comment]
@colby02184 The sample project is pulled from [okta-vue-sample](https://github.com/okta-samples/okta-vue-sample) by Okta CLI. You can ask there to see if there is a solution available.
