### ISSUE TITLE
How to access getAccessToken() outside of Vue component

### ISSUE THREAD

**Issue by OwenVey** [okta/okta-vue#69]
How can I access getAccessToken() outside of a Vue component? I'm trying to add an interceptor to my global Axios configuration in a JS file but since we can no longer import Vue in Vue 3, how should I go about this?

**Comment by shuowu** [comment]
@OwenVey `okta-vue` works by leverage the injected `okta-auth-js` instance, so you are always able to use APIs from okta-auth-js. 

API: https://github.com/okta/okta-auth-js#getaccesstoken

**Comment by OwenVey** [comment]
Thanks for the quick response @shuowu! So should I just export the ```OktaAuth``` object I'm creating and import that where I want access to those APIs?

**Comment by shuowu** [comment]
@OwenVey Correct. You can also access it by `this.$auth` in your Vue component.

**Comment by OwenVey** [comment]
Awesome, thank works! Thank you!
